//! R38.2e first dogfood — exercises a pinion-forge-generated reactive
//! struct from `ui/counter.pinion.xml` end-to-end.
//!
//! The compiled struct lives in `$OUT_DIR/counter.rs` and is pulled in
//! via the `include!` below; see `build.rs` for the codegen invocation.
//! `main` instantiates one Counter under an Owner, mutates the signal,
//! and prints the derived `display` computed value after each write —
//! validates `Signal::set` propagation, `Computed` memoization, and
//! chained `Computed`-of-`Computed` read order, all in a closed loop
//! with no external runtime.

use pinion_core::reactive::Owner;

// Generated by `build.rs` from `ui/counter.pinion.xml`. The included
// file defines `pub struct Counter { count, doubled, display }` plus
// its constructor `Counter::new(&Owner) -> Self`.
include!(concat!(env!("OUT_DIR"), "/counter.rs"));

fn main() {
    let owner = Owner::new();
    let counter = Counter::new(&owner);

    println!("initial:           {}", counter.display.get());

    counter.count.set(5);
    println!("after count.set(5):  {}", counter.display.get());

    counter.count.set(10);
    println!("after count.set(10): {}", counter.display.get());

    // Direct read of intermediate computed verifies the chained
    // dependency works (display reads doubled reads count).
    println!("final doubled:     {}", counter.doubled.get());
}
