[package]
name = "pinion-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Render loop and SCE hierarchical state machinery"

[dependencies]
pinion-core = { path = "../pinion-core", version = "0.0.1" }

[lints]
workspace = true
