#!/usr/bin/env python3
"""R1641 — tests for the pin-sync gate.

`pin_sync.py --check-dual-pin` is a push gate, and this project's standing rule
for a gate is that the gate itself is tested: `pre-push` runs the demo harness's
tests, the focus population's tests, the census selftests, the counterfactual
driver's tests and the blast-radius selftest before trusting any of them, after
R1522 found the tally reporting numbers whose own selftest had never run.

Every check below states a property some earlier version of the tool got wrong
or could not answer, so a failure here names the regression rather than a line
number.

Run from the workspace root:
    python3 tools/test_pin_sync.py
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pin_sync import (  # noqa: E402
    PINION_URL,
    SCE_SUBMODULE,
    SCE_URL,
    PinError,
    check_dual_pin,
    dedupe,
    index_gitlink,
    lock_rev,
    lock_source_revs,
    main,
    manifest_rev,
    only_shas_differ,
    present_consumers,
    rewrite_manifest,
)

FAILURES: list[str] = []
CHECKS = 0

A = "a" * 40
B = "b" * 40
C = "c" * 40


def check(condition: bool, what: str) -> None:
    global CHECKS  # noqa: PLW0603
    CHECKS += 1
    if not condition:
        FAILURES.append(what)


def raises(fn, what: str) -> None:
    """Assert `fn` raises PinError — the tool's own 'caller must fix' signal."""
    global CHECKS  # noqa: PLW0603
    CHECKS += 1
    try:
        fn()
    except PinError:
        return
    except Exception as exc:  # noqa: BLE001 — a traceback is itself the defect
        FAILURES.append(f"{what} (raised {type(exc).__name__}, not PinError)")
        return
    FAILURES.append(what)


def manifest_text(pinion: str, sce: str) -> str:
    """A consumer manifest shaped like the real ones: commented, multi-line."""
    return f"""# TO TAKE A NEW PINION: see tools/pin_sync.py.
[workspace.dependencies]
# A dozen lines of rationale live here in the real file, and a round-tripping
# TOML writer would not preserve them. Mentioning {A[:7]} in prose, too.
pinion-core = {{ git = "{PINION_URL}", rev = "{pinion}" }}
pinion-rpc = {{ git = "{PINION_URL}", rev = "{pinion}", default-features = false }}
sce-rust-runtime = {{ git = "{SCE_URL}", rev = "{sce}", default-features = false }}
serde = {{ version = "1" }}
"""


def lock_text(*sources: tuple[str, str]) -> str:
    body = "\n".join(
        f'[[package]]\nname = "pkg{i}"\nversion = "0.1.0"\n'
        f'source = "git+{url}?rev={rev}#{rev}"\n'
        for i, (url, rev) in enumerate(sources)
    )
    return f"# This file is automatically @generated by Cargo.\nversion = 3\n\n{body}"


def git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )


def make_pinion(root: Path, *, manifest_sce: str, lock_sce: str | None,
                gitlink: str | None) -> Path:
    """A minimal pinion-shaped repo: manifest, lock, and a vendor/sce gitlink.

    The gitlink is written straight into the index with `update-index
    --cacheinfo`, so the fixture needs no second repository to point at. That is
    the same object the real superproject records, which is the point: the check
    reads what a commit would publish, not what happens to be checked out.
    """
    root.mkdir(parents=True, exist_ok=True)
    git(root, "init", "-q")
    (root / "Cargo.toml").write_text(
        f'[workspace.dependencies]\n'
        f'sce-rust-runtime = {{ git = "{SCE_URL}", rev = "{manifest_sce}" }}\n'
        f'sce-build = {{ git = "{SCE_URL}", rev = "{manifest_sce}" }}\n',
        encoding="utf-8",
    )
    if lock_sce is not None:
        (root / "Cargo.lock").write_text(lock_text((SCE_URL, lock_sce)), encoding="utf-8")
    if gitlink is not None:
        git(root, "update-index", "--add", "--cacheinfo",
            f"160000,{gitlink},{SCE_SUBMODULE}")
    return root


def main_test() -> int:
    # ---- manifest reader -------------------------------------------------
    text = manifest_text(A, B)
    check(manifest_rev(text, PINION_URL) == A, "manifest_rev reads the pinion rev")
    check(manifest_rev(text, SCE_URL) == B, "manifest_rev reads the SCE rev")
    check(
        manifest_rev(text, "https://example.invalid/other.git") is None,
        "an absent dependency reads as None, not as an error",
    )
    # A 40-hex inside a comment must not be mistaken for a pin: the reader is
    # anchored to `git = "<url>"` lines, and the fixture puts a sha in prose.
    check(
        manifest_rev(text, PINION_URL) == A,
        "a sha mentioned in a comment does not become a second named rev",
    )
    raises(
        lambda: manifest_rev(
            text + f'pinion-cli = {{ git = "{PINION_URL}", rev = "{C}" }}\n',
            PINION_URL,
        ),
        "drift INSIDE one manifest raises instead of picking a line",
    )

    # ---- lock reader -----------------------------------------------------
    one = lock_text((PINION_URL, A), (SCE_URL, B))
    check(lock_rev(one, PINION_URL, where="t") == A, "lock_rev reads the pinion rev")
    check(lock_rev(one, SCE_URL, where="t") == B, "lock_rev reads the SCE rev")
    check(
        lock_rev(lock_text(), PINION_URL, where="t") is None,
        "a lock naming no such source reads as None",
    )
    # The pre-R1641 reader returned the first match, which made the lock the one
    # place drift could hide — while the docstring called it the authority.
    raises(
        lambda: lock_rev(
            lock_text((PINION_URL, A), (PINION_URL, C)), PINION_URL, where="t"
        ),
        "two revs for one URL in a lock raise instead of returning the first",
    )
    # Equality on the URL, not prefix: a sibling repo whose URL starts the same
    # way must not answer for this one.
    sibling = "https://github.com/newmassrael/pinion-extras.git"
    check(
        lock_rev(lock_text((sibling, C)), PINION_URL, where="t") is None,
        "a URL that merely starts with the target's does not answer for it",
    )
    check(
        lock_source_revs(lock_text((sibling, C)), sibling) == {C},
        "and that sibling still reads correctly under its own URL",
    )
    raises(
        lambda: lock_source_revs(
            f'source = "git+{PINION_URL}?rev={A}#{B}"\n', PINION_URL
        ),
        "a lock whose asked-for rev differs from the resolved one raises",
    )

    # ---- the rewrite safety property ------------------------------------
    check(only_shas_differ(f"rev = {A}", f"rev = {B}"), "only_shas_differ ignores shas")
    check(
        not only_shas_differ(f"rev = {A}", f"rev = {A}, default-features = false"),
        "only_shas_differ catches a change outside the sha",
    )
    check(
        not only_shas_differ(f"rev = {A}", f"rev = {A}{A}"),
        "and catches a sha count that changed",
    )

    with tempfile.TemporaryDirectory() as tmp:
        consumer = Path(tmp) / "consumer"
        consumer.mkdir()
        original = manifest_text(A, B)
        (consumer / "Cargo.toml").write_text(original, encoding="utf-8")

        changed = rewrite_manifest(
            consumer, {PINION_URL: C, SCE_URL: A}, dry_run=True
        )
        check(changed == 3, f"dry-run counts all three rev lines (got {changed})")
        check(
            (consumer / "Cargo.toml").read_text(encoding="utf-8") == original,
            "dry-run writes nothing",
        )

        changed = rewrite_manifest(
            consumer, {PINION_URL: C, SCE_URL: A}, dry_run=False
        )
        after = (consumer / "Cargo.toml").read_text(encoding="utf-8")
        check(changed == 3, "the real rewrite changes the same three lines")
        # Both URLs in ONE pass. Two passes would make the abort guarantee
        # per-URL, leaving a manifest half-rewritten when the second aborts.
        check(manifest_rev(after, PINION_URL) == C, "pinion lines were rewritten")
        check(manifest_rev(after, SCE_URL) == A, "SCE lines were rewritten in the same pass")
        check(
            only_shas_differ(original, after),
            "the rewritten file differs from the original ONLY in 40-hex tokens",
        )
        check(
            "A dozen lines of rationale" in after and "serde" in after,
            "comments and unrelated dependencies survive verbatim",
        )
        check(
            rewrite_manifest(consumer, {PINION_URL: C, SCE_URL: A}, dry_run=False) == 0,
            "a second identical rewrite is a no-op, so the tool is idempotent",
        )

    # ---- consumer list ---------------------------------------------------
    check(
        dedupe([Path("/a"), Path("/b"), Path("/a")]) == [Path("/a"), Path("/b")],
        "a repo listed twice is read once, in first-seen order",
    )
    with tempfile.TemporaryDirectory() as tmp:
        here, gone = Path(tmp) / "here", Path(tmp) / "gone"
        here.mkdir()
        (here / "Cargo.toml").write_text("[workspace]\n", encoding="utf-8")
        check(
            present_consumers([here, gone]) == [here],
            "an absent consumer is skipped, not treated as drift",
        )
        raises(
            lambda: present_consumers([gone]),
            "a check with NOTHING to verify fails rather than reading as passed",
        )

    # ---- the dual pin ----------------------------------------------------
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)

        aligned = make_pinion(root / "aligned", manifest_sce=A, lock_sce=A, gitlink=A)
        check(check_dual_pin(aligned) == [], "an aligned dual pin reports no problem")
        check(index_gitlink(aligned, SCE_SUBMODULE) == A, "the index gitlink is read")

        # The case the Cargo.toml comment describes and nothing enforced: the
        # manifest bumped without the submodule.
        drifted = make_pinion(root / "drifted", manifest_sce=A, lock_sce=A, gitlink=B)
        problems = check_dual_pin(drifted)
        check(len(problems) == 1, f"a gitlink bump alone is one problem (got {problems})")
        check(
            SCE_SUBMODULE in problems[0] and A[:7] in problems[0] and B[:7] in problems[0],
            "and the message names both sides so the fix is obvious",
        )

        stale = make_pinion(root / "stale", manifest_sce=A, lock_sce=B, gitlink=A)
        check(
            any("Cargo.lock" in p for p in check_dual_pin(stale)),
            "a manifest bumped without resolving the lock is caught",
        )

        nolink = make_pinion(root / "nolink", manifest_sce=A, lock_sce=A, gitlink=None)
        check(
            any(SCE_SUBMODULE in p for p in check_dual_pin(nolink)),
            "a missing gitlink is a problem, not an unchecked clause",
        )

        # No manifest side at all: raising beats reporting "aligned" about a
        # pin the file does not state.
        empty = root / "empty"
        empty.mkdir()
        git(empty, "init", "-q")
        (empty / "Cargo.toml").write_text("[workspace]\n", encoding="utf-8")
        raises(
            lambda: check_dual_pin(empty),
            "a repo naming no SCE dependency raises rather than passing vacuously",
        )

        # ---- argument combinations ---------------------------------------
        ok = str(aligned)
        check(main(["--check-dual-pin", "--pinion", ok]) == 0,
              "--check-dual-pin exits 0 on an aligned repo")
        check(main(["--check-dual-pin", "--pinion", str(drifted)]) == 1,
              "--check-dual-pin exits 1 on drift")
        check(main(["--check-dual-pin", A, "--pinion", ok]) == 1,
              "a check that is handed a rev is rejected")
        check(main(["--check", "--dry-run", "--pinion", ok]) == 1,
              "--dry-run with --check is rejected rather than silently ignored")
        check(main(["--check", "--check-dual-pin", "--pinion", ok]) == 1,
              "the two check modes are not combined")
        check(main([A, "--head", "--pinion", ok]) == 1,
              "a rev and --head together are rejected")
        check(main(["--pinion", ok, "--repo", ok]) == 1,
              "an invocation naming no action does nothing and says so")
        # A consumer check on a repo whose own pin disagrees must not report the
        # consumer clauses: they derive the expected SCE rev from exactly that pin.
        check(
            main(["--check", "--pinion", str(drifted), "--repo", ok]) == 1,
            "--check refuses to state consumer clauses on a self-inconsistent pin",
        )

    print(f"pin-sync tests: {CHECKS} checks, {len(FAILURES)} failure(s)")
    for failure in FAILURES:
        print(f"  FAIL: {failure}", file=sys.stderr)
    return 1 if FAILURES else 0


if __name__ == "__main__":
    sys.exit(main_test())
